### ISSUE TITLE
BaseHTTPServer not found

### ISSUE THREAD

**Issue by CyberFinn69** [luizpv/ipgrab#1]
When I put the ip-grab.py file in CMD, it says that the module BaseHTTPServer (line 1) doesn't exist. Is there some way to fix this?

**Comment by Cipherprobe** [comment]
The module BaseHTTPServer was for Python version 2, which was what this was coded in. The new Python 3 release changed the BaseHTTPServer name (so the name is non-existent now) to http.server. So you edit line 1 to http.server instead of BaseHTTPServer, like: from http.server import HTTPServer, BaseHTTPRequestHandler

**Comment by luizviana** [comment]
I updated the tool, now you can run it with python3
